In [1]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [2]:
engine = create_engine('mysql+mysqlconnector://root:Mysql712%40@localhost/CustomerPulse')

In [3]:
df = pd.read_excel('C:/Users/prach/Downloads/Online Retail.xlsx')
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.shape

(541909, 8)

In [5]:
df.to_sql('online_retail',engine,if_exists='replace',index=False)

541909

In [6]:
df.head(25)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom

In [7]:
df = df.loc[df['Country'] == 'United Kingdom']

In [8]:
df.shape

(495478, 8)

In [9]:
df=df.dropna(subset='CustomerID')

In [10]:
df.shape

(361878, 8)

In [11]:
df['InvoiceNo'].str[0].unique()

array([nan, 'C'], dtype=object)

In [12]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [13]:
df['InvoiceNo'].dtype

dtype('O')

In [14]:
df['InvoiceNo'].apply(type).unique()

array([<class 'int'>, <class 'str'>], dtype=object)

In [15]:
df = df.loc[df['InvoiceNo'].astype(str).str[0] != 'C']

In [16]:
df.shape

(354345, 8)

In [17]:
(df['Quantity']<0).sum()

np.int64(0)

In [18]:
df.loc[df['UnitPrice']<=0].shape

(24, 8)

In [19]:
df.loc[df['UnitPrice']<=0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,2010-12-16 14:36:00,0.0,16560.0,United Kingdom
47068,540372,22090,PAPER BUNTING RETROSPOT,24,2011-01-06 16:41:00,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,2011-01-06 16:41:00,0.0,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,2011-01-13 15:10:00,0.0,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,2011-03-23 10:25:00,0.0,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,2011-03-30 12:45:00,0.0,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,2011-04-04 14:42:00,0.0,14410.0,United Kingdom
187613,553000,47566,PARTY BUNTING,4,2011-05-12 15:21:00,0.0,17667.0,United Kingdom
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,2011-07-26 12:24:00,0.0,16818.0,United Kingdom
285657,561916,M,Manual,1,2011-08-01 11:44:00,0.0,15581.0,United Kingdom
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 12:22:00,0.0,16133.0,United Kingdom
361825,568384,M,Manual,1,2011-09-27 09:46:00,0.0,12748.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,2011-10-06 08:17:00,0.0,15804.0,United Kingdom
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,2011-10-26 14:36:00,0.0,18059.0,United Kingdom
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,2011-11-03 11:47:00,0.0,14110.0,United Kingdom
446125,574879,22625,RED KITCHEN SCALES,2,2011-11-07 13:22:00,0.0,13014.0,United Kingdom
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,2011-11-07 16:34:00,0.0,13985.0,United Kingdom
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,2011-11-07 16:34:00,0.0,13985.0,United Kingdom
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,2011-11-10 11:49:00,0.0,13081.0,United Kingdom
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,2011-11-10 11:49:00,0.0,13081.0,United Kingdom
479079,577129,22464,HANGING METAL HEART LANTERN,4,2011-11-17 19:52:00,0.0,15602.0,United Kingdom
485985,577696,M,Manual,1,2011-11-21 11:57:00,0.0,16406.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256.0,United Kingdom

In [20]:
df = df.loc[df['UnitPrice'] > 0]

In [21]:
df.shape

(354321, 8)

In [22]:
df.duplicated(subset=['InvoiceNo','StockCode']).sum()

np.int64(9886)

In [23]:
df = df.drop_duplicates(subset=['InvoiceNo','StockCode'])

In [24]:
df.shape

(344435, 8)

In [25]:
 df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [26]:
df.shape

(344435, 8)

In [27]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [28]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [29]:
reference_date = df['InvoiceDate'].max()

In [30]:
reference_date

Timestamp('2011-12-09 12:49:00')

In [31]:
rfm = df.groupby('CustomerID').agg(
    Recency = ('InvoiceDate','max'),
    Frequency = ('InvoiceNo','count'),
    Monetary = ('TotalPrice','sum')
)

In [32]:
rfm.head()

                       Recency  Frequency  Monetary
CustomerID
12346.0    2011-01-18 10:01:00          1  77183.60
12747.0    2011-12-07 14:34:00        103   4196.01
12748.0    2011-12-09 12:20:00       4284  32448.84
12749.0    2011-12-06 09:56:00        199   4090.88
12820.0    2011-12-06 15:12:00         59    942.34

In [33]:
rfm['Recency'] = (reference_date - rfm['Recency']).dt.days

In [34]:
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         325          1  77183.60
12747.0           1        103   4196.01
12748.0           0       4284  32448.84
12749.0           3        199   4090.88
12820.0           2         59    942.34

In [35]:
rfm.shape

(3920, 3)

In [36]:
rfm.describe()

           Recency    Frequency       Monetary
count  3920.000000  3920.000000    3920.000000
mean     91.208418    87.866071    1849.708488
std      99.533854   210.238164    7470.357288
min       0.000000     1.000000       3.750000
25%      17.000000    16.000000     295.262500
50%      50.000000    40.000000     638.055000
75%     142.000000    97.000000    1562.585000
max     373.000000  7477.000000  259657.300000

In [37]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
TotalPrice            float64
dtype: object

In [38]:
rfm.index = rfm.index.astype(int)

In [39]:
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346           325          1  77183.60
12747             1        103   4196.01
12748             0       4284  32448.84
12749             3        199   4090.88
12820             2         59    942.34

In [40]:
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=4, labels=[4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'], q=4, labels=[1,2,3,4])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], q=4, labels=[1,2,3,4])

In [41]:
rfm.head()

            Recency  Frequency  Monetary R_Score F_Score M_Score
CustomerID
12346           325          1  77183.60       1       1       4
12747             1        103   4196.01       4       4       4
12748             0       4284  32448.84       4       4       4
12749             3        199   4090.88       4       4       4
12820             2         59    942.34       4       3       3

In [42]:
rfm.dtypes

Recency         int64
Frequency       int64
Monetary      float64
R_Score      category
F_Score      category
M_Score      category
dtype: object

In [43]:
rfm['R_Score'] = rfm['R_Score'].astype(int)
rfm['F_Score'] = rfm['F_Score'].astype(int)
rfm['M_Score'] = rfm['M_Score'].astype(int)

In [44]:
rfm['RFM_Score'] = rfm['R_Score']+rfm['F_Score']+rfm['M_Score']

In [45]:
rfm.head()

            Recency  Frequency  Monetary  R_Score  F_Score  M_Score  RFM_Score
CustomerID
12346           325          1  77183.60        1        1        4          6
12747             1        103   4196.01        4        4        4         12
12748             0       4284  32448.84        4        4        4         12
12749             3        199   4090.88        4        4        4         12
12820             2         59    942.34        4        3        3         10

In [46]:
rfm['Segment'] = pd.cut(rfm['RFM_Score'], bins=[2,4,6,9,12], labels=['Lost','At Risk','Loyal','Champions'])

In [47]:
rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
CustomerID,,,,,,,,
12346,325,1,77183.60,1,1,4,6,At Risk
12747,1,103,4196.01,4,4,4,12,Champions
12748,0,4284,32448.84,4,4,4,12,Champions
12749,3,199,4090.88,4,4,4,12,Champions
12820,2,59,942.34,4,3,3,10,Champions

In [48]:
rfm['Segment'].value_counts()

Segment
Loyal        1196
Champions    1135
At Risk       901
Lost          688
Name: count, dtype: int64

In [49]:
rfm.to_sql('rfm_scores', engine, if_exists='replace', index=True)

3920

In [50]:
rfm['Churned'] = (rfm['Recency']>90).astype(int)

In [51]:
rfm['Churned'].value_counts()

Churned
0    2617
1    1303
Name: count, dtype: int64

In [52]:
rfm.to_sql('rfm_scores',engine, if_exists='replace', index=True)

3920

In [53]:
rfm.head()

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment,Churned
CustomerID,,,,,,,,,
12346,325,1,77183.60,1,1,4,6,At Risk,1
12747,1,103,4196.01,4,4,4,12,Champions,0
12748,0,4284,32448.84,4,4,4,12,Champions,0
12749,3,199,4090.88,4,4,4,12,Champions,0
12820,2,59,942.34,4,3,3,10,Champions,0

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [56]:
x = rfm[['R_Score','F_Score','M_Score']]
y = rfm['Churned']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [57]:
model = RandomForestClassifier(class_weight='balanced',random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [58]:
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.78      0.86       519
           1       0.68      0.94      0.79       265

    accuracy                           0.83       784
   macro avg       0.82      0.86      0.82       784
weighted avg       0.87      0.83      0.83       784

In [59]:
print('Training Accuracy',model.score(x_train,y_train))
print('Testing Accuracy',model.score(x_test,y_test))

Training Accuracy 0.8769132653061225
Testing Accuracy 0.8303571428571429

In [60]:
pd.Series(model.feature_importances_, index = ['R_Score','F_Score','M_Score'])

R_Score    0.826246
F_Score    0.097761
M_Score    0.075992
dtype: float64

In [64]:
import joblib

joblib.dump(model,'customer_pulse_churn_model.pkl')

['customer_pulse_churn_model.pkl']

In [62]:
loaded_model = joblib.load('churn_model.pkl') 
loaded_model.predict(x_test)

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

            Actual  Predicted
CustomerID
13956            0          0
14520            0          0
17446            1          1
17678            1          1
15265            1          1
16083            1          0
13615            1          1
15244            0          1
17863            0          0
16363            0          1
13151            1          1
14820            0          0
16762            0          0
16187            0          0
16081            0          0
15777            1          1
15395            1          1
13607            0          0
12831            1          1
15043            0          0

In [66]:
rfm.to_csv("rfm_dashboard.csv",index=True)